### ISSUE TITLE
Related to the download for dataset

### ISSUE THREAD

**Issue by cyfedu-dlut** [IT3DEgo/IT3DEgo#3]
Hello, this is an amazing work! I have noticed that the dataset download continuously fails, even though I have enabled a VPN. No matter whether I use Google Drive, wget, or other methods, the download fails. Are there any other solutions to resolve this issue? Are there alternative download channels available? Thank you for your response.

**Comment by sinhasaptarshi** [comment]
How did you solve this issue?

**Comment by IT3DEgo** [comment]
Just copy-paste my response from the email (since I received some similar issues over the email) and this seem fixing similar issue in the past:

I have just tried the download link and it works fine for me. I'm able to download with a different google account from a different device. Could you maybe try to download again using chrome (not in incognito mode) with a google account (sign-in this account in chrome)? Previously we have seen one download issue (Too many users have viewed/accessed this file and google drive won't let you download). To fix this particular problem, simply create and log into your google account in chrome and try to download again, the problem will be fixed.

**Comment by sinhasaptarshi** [comment]
I tried that. and i still keep getting that error. Is there any alternate link to download the dataset?
